const teamsArray: { value: string; name: string }[] = [
  { value: "ALPECIN", name: "Alpecin - Premier Tech" },
  { value: "BAHRAIN", name: "Team Bahrain Victorious" },
  { value: "CAJA-RURAL", name: "Caja Rural - Seguros RGA" },
  { value: "COFIDIS", name: "Cofidis" },
  { value: "DEC-CMA", name: "Decathlon CMA CGM" },
  { value: "EFEDUCATION", name: "EF Education - EasyPost" },
  { value: "GROUP-FDJ", name: "Groupama - FDJ United" },
  { value: "INEOS", name: "Netcompany INEOS Cycling Team" },
  { value: "JAYCO", name: "Team Jayco AlUla" },
  { value: "LIDL", name: "Lidl - Trek" },
  { value: "LOTTO", name: "Lotto - Intermarché" },
  { value: "MOVISTAR", name: "Movistar Team" },
  { value: "NSN", name: "NSN Cycling Team" },
  { value: "PICNIC", name: "Team Picnic - PostNL" },
  { value: "Q365", name: "Pinarello - Q36.5 Pro Cycling Team" },
  { value: "REDBULL-BORA", name: "Red Bull - BORA - Hansgrohe" },
  { value: "SOUDAL", name: "Soudal Quick-Step" },
  { value: "TOTAL", name: "Team TotalEnergies" },
  { value: "TUDOR", name: "Tudor Pro Cycling Team" },
  { value: "UAE", name: "UAE Team Emirates XRG" },
  { value: "UNO-X", name: "Uno-X Mobility" },
  { value: "VISMA", name: "Visma - Lease a Bike" },
  { value: "ASTANA", name: "XDS Astana Team" },
];

export default teamsArray;
