const teamsArray: { value: string; name: string }[] = [
  { value: "TEAM-VISMA", name: "Team Visma" },
  { value: "UAE", name: "UAE Team Emirates XRG" },
  { value: "JAYCO", name: "Jayco Alula" },
  { value: "INEOS", name: "Ineos Grenadiers" },
  { value: "LIDL", name: "LIDL - Trek" },
  { value: "DEC-AG2R", name: "Decathlon AG2R" },
  { value: "BAHRAIN", name: "Bahrain Victorious" },
  { value: "SOUDAL", name: "Soudal Quick-Step" },
  { value: "GROUP-FDJ", name: "Groupama - FDJ" },
  { value: "REDBULL-BORA", name: "Red Bull - BORA - Hansgrohe" },
  { value: "ALP-DEC", name: "Alpecin - Deceuninck" },
  { value: "EFEDUCATION", name: "EF Education - Easypost" },
  { value: "LOTTO", name: "Lotto" },
  { value: "ISRAEL", name: "Israel - Premier Tech" },
  { value: "COFIDIS", name: "Cofidis" },
  { value: "MOVISTAR", name: "Movistar Team" },
  { value: "ARKEA", name: "Arkea - B&B Hotels" },
  { value: "INT-WAN", name: "Intermarché - Wanty" },
  { value: "ASTANA", name: "XDS Astana team" },
  { value: "TOTAL", name: "TotalEnergies" },
  { value: "UNO-X", name: "Uno-X Mobility" },
  { value: "TUDOR", name: "Tudor Pro Cycling team" },
  { value: "PICNIC", name: "Team Picnic PostNL" },
];

export default teamsArray;
